### ISSUE TITLE
Some repositories skipped when matching up apps to repositories

### ISSUE THREAD

**Issue by rsjaffe** [dcmeglio/hubitat-packagemanager#97] opened 2020-05-20 17:56 UTC
Only 14 repositories are checked even though 18 are in https://raw.githubusercontent.com/dcmeglio/hubitat-packagerepositories/master/repositories.json. For example, tonesto7 is skipped (which is how I detected this--I have an app by him that didn't get matched up). Following is the log for when I tried matching up repositories (time is PST UTC-8).

app:2572020-05-20 07:48:00.670 am infoMatching up packages
app:2572020-05-20 07:47:51.251 am infoRefreshing apwelsh
app:2572020-05-20 07:47:32.974 am infoRefreshing nh.schottfam
app:2572020-05-20 07:47:26.789 am infoRefreshing imnotbob
app:2572020-05-20 07:47:21.211 am infoRefreshing MFornander
app:2572020-05-20 07:47:10.153 am infoRefreshing storageaanarchy (SANdood)
app:2572020-05-20 07:46:23.765 am infoRefreshing dman2306
app:2572020-05-20 07:46:23.760 am warnFound a bad manifest https://raw.githubusercontent.com/djdizzyd/hubitat/master/packages/zoozZen31.json
app:2572020-05-20 07:46:23.744 am errorError downloading https://raw.githubusercontent.com/djdizzyd/hubitat/master/packages/zoozZen31.json: groovyx.net.http.HttpResponseException: Not Found
app:2572020-05-20 07:45:09.819 am infoRefreshing bcopeland
app:2572020-05-20 07:45:01.758 am infoRefreshing RMoRobert (BertABCD1234)
app:2572020-05-20 07:44:53.010 am infoRefreshing Miles Budnek (@mbudnek)
app:2572020-05-20 07:44:39.888 am infoRefreshing Matthew (@scottma61)
app:2572020-05-20 07:44:31.922 am infoRefreshing Inovelli
app:2572020-05-20 07:44:19.726 am infoRefreshing Dave Gutheinz(DavGut)
app:2572020-05-20 07:42:44.308 am infoRefreshing BPTWorld
app:2572020-05-20 07:42:23.393 am infoRefreshing AaronW
app:2572020-05-20 07:42:23.262 am infoRetrieving list of installed drivers
app:2572020-05-20 07:42:22.953 am infoRetrieving list of installed apps

**Comment by dcmeglio** [comment] 2020-05-20 19:39
Someone reported a bug that I haven't tracked down yet, if you go to the settings, is tonesto's checked off as enabled? If not please enable it and try again. Let me know if it still doesn't work. It's a bug either way, this will just help me know if there is a 2nd bug or if it's all the same bug.

**Comment by rsjaffe** [comment] 2020-05-20 20:40
It was not enabled. I enabled it (and all the others that weren't enabled). Match-up is now working.

I find that having some of the new repositories show up as unenabled is surprising behavior and probably should be changed.

**Comment by dcmeglio** [comment] 2020-05-20 20:44
It's a bug, it shouldn't do it that way but I haven't figured it out yet.

**Comment by dcmeglio** [comment] 2020-05-26 14:48
Marking as a duplicate of #102

**Closed** 2020-05-26 14:49 UTC
