### ISSUE TITLE
Separate manifest for the Beta version of a package

### ISSUE THREAD

**Issue by markus-li** [dcmeglio/hubitat-packagemanager#83] opened 2020-05-03 17:31 UTC
Since the Beta version of the package is hosted in a separate branch it would make the whole process of having a beta package much more streamlined if it would be possible to split the manifest.

This was discussed in the community forum [here](https://community.hubitat.com/t/beta-hubitat-package-manager/38016/183?u=markus).

Example repository with "betaLocation" specified:
https://github.com/markus-li/Hubitat/blob/release/repository.json

Example Beta package Manifest:
https://github.com/markus-li/Hubitat/blob/development/packageManifestBeta.json

Example Release package Manifest:
https://github.com/markus-li/Hubitat/blob/release/packageManifestBeta.json

**Comment by markus-li** [comment] 2020-05-06 02:08
May I ask why you prefer to put the link in the package manifest and not in the repository JSON? If in the repository JSON it would open up to have ONLY beta released until it is ready for a non-beta release. It also won't depend on the release manifest being updated with changes to the beta release URL.

**Comment by dcmeglio** [comment] 2020-05-06 23:39
I definitely see what you're saying, the challenge is the value of the "location" is basically the primary key for the state.manifests variable that drives everything. So if there is no "location" (beta only), I don't really have my "key" to identify the package. So not so much that I "prefer" it, it's just a major change to do what you're suggesting. I'll give it more thought though.

**Comment by markus-li** [comment] 2020-05-07 05:44
Maybe switch to UUIDs calculated from the current location string if a UUID is not specifically set, and require UUID to be set if locationBeta is alone?

**Comment by dcmeglio** [comment] 2020-05-07 21:17
The problem isn't coming up with a different id, it's taking the time to rewrite all of the code that expects the ID to be the URL... it's pretty much used everywhere.

**Comment by markus-li** [comment] 2020-05-08 09:59
That is really to bad, if you reconsider and do it the "proper" way I'd be very happy, but I understand that it may be a lot of work.

**Comment by dcmeglio** [comment] 2020-05-08 15:44
To be clear, I'm not saying no, I'm just saying I have to think about it. Whenever a programming task seems very difficult, I first try to say "maybe I'm thinking about the problem the wrong way." Sometimes there's a solution that isn't obvious at first. I'm going to keep thinking on it and see what I can come up with.

**Comment by dcmeglio** [comment] 2020-05-10 17:15
I'm going to leave this undocumented in the 1.4.0 release going out today and then I'll take another look. I really want to get HPM out of beta and my plan is 1.4.0 will be released as beta and if no bugs are found I'll promote it to stable. I want to get more devs signed up and I know a few are waiting for it to be considered stable first. Then from there I'll work on more feature additions

**Closed** 2020-05-11 01:11 UTC
Labels: enhancement
